replicaCount: 1

image:
  repository: raymondcai/ubuntu-flask
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80          # Cluster port
  targetPort: 5000  # Container port
  nodePort: 30080   # Exposed node port (between 30000–32767)

containerPort: 5000

