replicaCount: 1

image:
  repository: raymondcai/ubuntu-flask
  tag: b89129de712b79207debd180a80277ee6b5d3b17
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80          # Cluster port
  targetPort: 5000  # Container port
  nodePort: 30080   # Exposed node port (between 30000–32767)

containerPort: 5000

